### ISSUE TITLE
Generate Code error - Matlab_R2019b

### ISSUE THREAD

**Issue by omkarg** [EFeru/bldc-motor-control-FOC#1]
Hi,
I am getting the following error when trying to generate code from Simulink model, could you please help me with this? I am using Matlab_R2019b version

### Build procedure for model: 'BLDCmotor_FOC_R2017b_fixdt' aborted due to an error.
Error in S-function 'BLDCmotor_FOC_R2017b_fixdt/BLDC_model_closed/BLDC_model_sfcn': S-Function 'BLDC_model_sf' does not exist
Component:Simulink | Category:Block diagram error
Error in S-function 'BLDCmotor_FOC_R2017b_fixdt/PWM_gates/PWM_generator1/PWM_generator_sfcn': S-Function 'PWM_generator_sf' does not exist

**Comment by EFeru** [comment]
Did you run the init_model first? 
Are you able to simulate the model by pressing play?

**Comment by omkarg** [comment]
Yes,  I ran the init_model and it ran successfully. attached screenshot for reference.
But if I try to generate code from Simulink it gives that error 
 
<img width="618" alt="Screenshot 2021-04-15 at 11 58 15 PM" src="https://user-images.githubusercontent.com/3839628/114919960-8b7c2380-9e46-11eb-93e8-52e36b5e8611.png">

**Comment by omkarg** [comment]
These paths are also set in Matlab (attached screenshot)

<img width="1053" alt="Screenshot 2021-04-16 at 12 00 20 AM" src="https://user-images.githubusercontent.com/3839628/114920211-d302af80-9e46-11eb-8474-0189ffaf6d7f.png">

**Comment by omkarg** [comment]
Hi @EmanuelFeru ,

**Comment by omkarg** [comment]
Hi @EmanuelFeru ,

**Comment by omkarg** [comment]
Hi @EmanuelFeru , Is there something else that needs to be set? Or I checked for few resources online to fix this issue by running the mex command but I am unable to find the .c file for it. If you could help me that would be really great

**Comment by EFeru** [comment]
Are you able to run the model? And yes you need to install a c compiler to run and build the code. See here 
https://www.mathworks.com/support/requirements/supported-compilers.html
I have the first one MinGW. 

Also i used Matlab R2017b I am not sure if there are some incompatibility issue. Normally it should be upwards compatible.

**Comment by omkarg** [comment]
Yes the C compiler is already installed and I am able to run the model from Matlab as seen in the above screenshots but if I run it in Simulink it gives me this error. 
<img width="706" alt="Screenshot 2021-04-18 at 11 13 47 PM" src="https://user-images.githubusercontent.com/3839628/115155056-bdd28e80-a09b-11eb-8fee-17421872e271.png">

**Comment by EFeru** [comment]
This is an indication that the s functions are not compatible with the 2019b. I will give a try myself next day, I think I still have the 2019b version installed.

**Comment by omkarg** [comment]
@EmanuelFeru or you can upload the C file for the S functions and I can or anyone else who faces this issue can also generate the S functions.

**Comment by EFeru** [comment]
Is it possible to generate s-functions from C files?

**Comment by omkarg** [comment]
I was assuming this would solve the issue, hence mentioned about the C file https://in.mathworks.com/matlabcentral/answers/146644-error-in-s-funtion-s-function-test-does-not-exist.  and they had mentioned it here as well https://stackoverflow.com/questions/8953759/s-function-in-simulink-matlab/33988085

**Comment by omkarg** [comment]
@EmanuelFeru good afternoon. Is it working at your end on 2019b? or any idea on how I can generate the S functions with this version on matlab

**Comment by asti-softronic** [comment]
Hi,
I have the same problem (MATLAB version is: R2021a).
Could you upload the .c source for s-functions?
Thank you.
A.

**Comment by EFeru** [comment]
Hi,

I just opened the model in it's own folder location in Matlab R2019b and pressed Run. It worked without problem and produces same output as in 2017b.
![image](https://user-images.githubusercontent.com/24780745/115954019-ea990280-a4ee-11eb-8cbc-34d75c7966ae.png)
![image](https://user-images.githubusercontent.com/24780745/115954022-ef5db680-a4ee-11eb-8774-71270c5ab04f.png)


Edit:
If I type `mex -setup` I get this compiler:
![image](https://user-images.githubusercontent.com/24780745/115954172-cb4ea500-a4ef-11eb-87f4-e14288aabd37.png)

**Comment by EFeru** [comment]
@omkarg, I see you are using a Mac. I built the s functions on Windows, can that be the problem?

**Comment by omkarg** [comment]
@EmanuelFeru that can be the issue. How are you generating the S functions on your machine? If you can provide the files for S function I can try to generate it on my mac machine and see if that works.

**Comment by omkarg** [comment]
The compiler for mac is also different so may be it is because I am using mac machine it is not working

**Comment by omkarg** [comment]
@asti-softronic are you using a mac machine?

**Comment by EFeru** [comment]
To build i just Right click the block and then, go to Code generation and click make s-function.
I forgot to tell you, but the open model is also there, it is the commented block _open, right above the used block _closed. Have you tried with the open one?

**Comment by omkarg** [comment]
@EmanuelFeru Yes even I am using the same process to generate S functions but it does not work on mac machine. Yes i tried with open model , for closed model it is used to give 2 errors for open model it gives one error as per the screenshot. I have attached the open model config and the error screenshots. Can you extract the C code for the S function and provide, may be I can try it that way or if you have any other options I can try that
<img width="1317" alt="Screenshot 2021-05-03 at 3 39 15 PM" src="https://user-images.githubusercontent.com/3839628/116865444-49fdbd80-ac27-11eb-9b7f-73e9c3aa78b2.png">
<img width="1345" alt="Screenshot 2021-05-03 at 3 39 44 PM" src="https://user-images.githubusercontent.com/3839628/116865459-4ff39e80-ac27-11eb-8cf7-00db1bb26b6f.png">

**Comment by EFeru** [comment]
Inside the PWM_gates block there is also the open model. Try replacing the 6 pwm blocks with the open one. If you still have the error you can delete the 6 pwm blocks and connect line directly inside pwm_gates and try to run.

**Comment by omkarg** [comment]
@EmanuelFeru Yes, it works in open mode. But I will have to get the closed mode working for it to work in FOC right?

**Comment by EFeru** [comment]
No need for that. The closed part is the plant model not the controller. I closed the model just to have faster simulation time and in case someone does not have the Simulink motor model. But for the controller it doesn't matter if you use open or closed plant model.

**Comment by EFeru** [comment]
@omkarg Did you manage to make it run in 2019b?

**Comment by omkarg** [comment]
@EmanuelFeru Apologies for the late response. With the open model I was able to run it in 2019b version
